# Generated by Django 4.2.5 on 2023-09-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'verbose_name': 'Fotografia', 'verbose_name_plural': 'Fotografias'},
        ),
    ]
