# Generated by Django 4.2.5 on 2023-09-17 10:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'verbose_name': 'Fotografia', 'verbose_name_plural': 'Fotografia'},
        ),
        migrations.AlterModelManagers(
            name='fotografia',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
