# Generated by Django 4.2.5 on 2023-09-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_options_alter_fotografia_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'verbose_name': 'Fotografia', 'verbose_name_plural': 'Fotografias'},
        ),
    ]
