# Generated by Django 4.2.5 on 2023-09-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={},
        ),
    ]
